<div class="wrapper">
    <div class="container">
        <div class="row text-center">
            <div id="converter" class="col-md-8 col-md-offset-2 col-lg-10 col-lg-offset-1">
                <div id="history"></div>
                <div id="controls">
                    <?php
                        if (!empty($this->form)) {
                            echo $this->form;
                            echo "<button id='switch_currency' type='button' class='btn btn-primary btn-lg'>Switch Currency</button>";
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var allowed_currencies = <?php
        $currencies = [];
        foreach($this->allCurrencies as $currency => $rateObject) {
            array_push($currencies, $currency);
        }
        echo json_encode($currencies);

    ?>;
</script>